[project]
name = "laba1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Max", email = "maksym.plish.kb.2025@lpnu.ua" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
laba1 = "laba1:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
